---
title: Gerrymandering Metrics
format: typst
---

```{r}
#Set Up 
library(tidyverse)
precinct_data <- read_csv("data/g24_sov_by_g24_svprec_clean.csv")
precinct_congress <- precinct_data |>
    filter(!str_detect(svprec, "TOT")) |>
    filter(cddist > 0)
```

### 2024 Election Results and the 2024 District Map

```{r}
wasted_votes <- function(votes_a, votes_b) {
    total <- votes_a + votes_b
    needed <- floor(total/2) + 1
    ifelse(votes_a > votes_b, votes_a - needed, votes_a)
}
district_results <- precinct_congress |>
    group_by(cddist) |>
    summarize(dem_total = sum(demvote, na.rm = TRUE), rep_total = sum(repvote, na.rm = TRUE), two_party_total = dem_total + rep_total, .groups = "drop")

two_party_district <- district_results |>
    filter(dem_total > 0, rep_total > 0)

two_party_district <- two_party_district |>
    mutate(wasted_dem = wasted_votes(votes_a = dem_total, votes_b = rep_total), wasted_rep = wasted_votes(votes_a = rep_total, votes_b = dem_total))

total_wasted_dem <- sum(two_party_district$wasted_dem)
total_wasted_rep <- sum(two_party_district$wasted_rep)
total_two_party_votes <- sum(two_party_district$two_party_total)

efficiency_gap <- (total_wasted_rep - total_wasted_dem) / total_two_party_votes
efficiency_gap

```


### 2024 Election Results and the proposed 2025 District Map


```{r}
ab604_results <- read_csv("data/ab604_cd_results.csv")
ab604_district_results <- ab604_results |>
    rename(cddist = district, dem_total = uspdem01, rep_total = usprep01) |>
    mutate(two_party_total = dem_total + rep_total)

wasted_votes <- function(votes_a, votes_b) {
    total  <- votes_a + votes_b
    needed <- floor(total / 2) + 1
    ifelse(votes_a > votes_b, votes_a - needed, votes_a)
}
two_party_district <- ab604_district_results |>
    filter(dem_total > 0, rep_total > 0)

two_party_district <- two_party_district |>
    mutate(wasted_dem = wasted_votes(votes_a = dem_total, votes_b = rep_total), wasted_rep = wasted_votes(votes_a = rep_total, votes_b = dem_total))

total_wasted_dem <- sum(two_party_district$wasted_dem)
total_wasted_rep <- sum(two_party_district$wasted_rep)
total_two_party_votes <- sum(two_party_district$two_party_total)

efficiency_gap <- (total_wasted_rep - total_wasted_dem) / total_two_party_votes
efficiency_gap

```